apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
data:
  appsettings.json: |-
    {
      "MongoDb": {
        "ConnectionString": "",
        "LocalConnectionString": "mongodb://mongodb-service-lb",
        "DatabaseName": {
          "BookStore": "BookStore"
        }
      },
      "RabbitMq": {
        "Host": "amqp://rabbitmq-service-lb",
        "Username": "guest",
        "Password": "guest",
        "Queues": {
          "Borrowing": "borrowing-queue"
        }
      }
    }
