apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-borrowing-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrowing-service-app
  template:
    metadata:
      labels:
        app: borrowing-service-app
    spec:
      containers:
      - name: borrowing-service
        image: nghialoe/borrowing-service:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /app/config/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume
        configMap:
          name: bookstore-config
---
apiVersion: v1
kind: Service
metadata:
  name: borrowing-service-lb
spec:
  selector:
    app: borrowing-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
