apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-notification-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service-app
  template:
    metadata:
      labels:
        app: notification-service-app
    spec:
      containers:
      - name: notification-service
        image: nghialoe/notification-service:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /app/config/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume
        configMap:
          name: bookstore-config

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-lb
spec:
  selector:
    app: notification-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
